#!/usr/bin/env bash

# Installs Nginx with the following configurations:
## server
## Nginx should be listening on port 80
## When querying Nginx at its root / with a GET request (requesting a page)\
### using curl, it must return a page that contains the string Hello World!
## As an answer file, write a Bash script that configures a new Ubuntu machine\
### to respect above requirements (this script will be run on the server itself)
## You can’t use systemctl for restarting nginx

# Update the package lists
apt-get -y update

# Install Nginx
apt-get -y install nginx

# Create the index.html file
echo "Hello World!" > /var/www/html/index.html

# Configure Nginx to listen on port 80 and serve the index.html file
cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOF

# Restart Nginx
service nginx restart
