#!/usr/bin/env bash

# Update the package lists
apt-get -y update

# Install Nginx
apt-get -y install nginx

# Configure Nginx to listen on port 80
cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.nginx-debian.html;

    location / {
        echo "Hello World!";
    }
}
EOF

# Restart Nginx
service nginx restart
